version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - '5400:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  post-service:
    image: epamilyaskumin/k8s-course_post-service:1.0.1
    container_name: ${POSTSERVICE_CNAME}
    ports:
      - ${POSTSERVICE_PORT}:${APPLICATION_PORT}
    depends_on:
      - postgres
    env_file:
      - .env

  user-service:
    image: epamilyaskumin/k8s-course_user-service:1.0.1
    container_name: ${USERSERVICE_CNAME}
    ports:
      - ${USERSERVICE_PORT}:${APPLICATION_PORT}
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  db-data:
    name: k8s-db-data