version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5400:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  post-service:
    image: epamilyaskumin/k8s-course_post-service:1.0
    ports:
      - '8081:8080'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: database
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      USERSERVICE_URL: http://user-service:8080
      APPLICATION_PORT: '8080'

  user-service:
    image: epamilyaskumin/k8s-course_user-service:1.0
    ports:
      - '8082:8080'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: database
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      APPLICATION_PORT: '8080'

volumes:
  db-data:
    name: k8s-db-data