apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ include "my-chart.database-namespace" . }}
data:
  APPLICATION_PORT: '8080'
  DATABASE_CNAME: 'database.{{ include "my-chart.database-namespace" . }}'
  DATABASE_PORT: '5400'
  POSTSERVICE_CNAME: 'post-service.{{ include "my-chart.postservice-namespace" . }}'
  POSTSERVICE_PORT: '8081'
  USERSERVICE_CNAME: 'user-service.{{ include "my-chart.userservice-namespace" . }}'
  USERSERVICE_PORT: '8082'
  {{- include "my-chart.labels" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ include "my-chart.postservice-namespace" . }}
data:
  APPLICATION_PORT: '8080'
  DATABASE_CNAME: 'database.{{ include "my-chart.database-namespace" . }}'
  DATABASE_PORT: '5400'
  POSTSERVICE_CNAME: 'post-service.{{ include "my-chart.postservice-namespace" . }}'
  POSTSERVICE_PORT: '8081'
  USERSERVICE_CNAME: 'user-service.{{ include "my-chart.userservice-namespace" . }}'
  USERSERVICE_PORT: '8082'
  {{- include "my-chart.labels" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ include "my-chart.userservice-namespace" . }}
data:
  APPLICATION_PORT: '8080'
  DATABASE_CNAME: 'database.{{ include "my-chart.database-namespace" . }}'
  DATABASE_PORT: '5400'
  POSTSERVICE_CNAME: 'post-service.{{ include "my-chart.postservice-namespace" . }}'
  POSTSERVICE_PORT: '8081'
  USERSERVICE_CNAME: 'user-service.{{ include "my-chart.userservice-namespace" . }}'
  USERSERVICE_PORT: '8082'
  {{- include "my-chart.labels" . }}