spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5400}/posts
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  cloud:
    openfeign:
      client:
        config:
          user-service:
            url: ${USERSERVICE_URL:http://localhost:8082}

server:
  port: ${APPLICATION_PORT:8081}
  error:
    include-message: always
    include-binding-errors: always
