apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  namespace: k8s-course
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: epamilyaskumin/k8s-course_post-service:1.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: k8s-course-configmap
            - secretRef:
                name: k8s-course-secret
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  type: ClusterIP
  ports:
    - name: "default-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: post-service