spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5400/users}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  cloud:
    openfeign:
      client:
        config:
          post-service:
            url: ${USERSERVICE_URL:http://localhost:8081}

server:
  port: ${APPLICATION_PORT:8082}
  error:
    include-message: always
    include-binding-errors: always
