apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-course-configmap
  namespace: k8s-course
data:
  APPLICATION_PORT: '8080'
  DATABASE_CNAME: 'database'
  DATABASE_PORT: '5400'
  POSTSERVICE_CNAME: 'post-service'
  POSTSERVICE_PORT: '8081'
  USERSERVICE_CNAME: 'user-service'
  USERSERVICE_PORT: '8082'