apiVersion: v1
kind: Service
metadata:
  name: database-ep
  namespace: database-k8s-course
spec:
  type: NodePort
  ports:
    - name: 'node-port'
      nodePort: 30000
      port: 5432
  selector:
    app: database
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-ep
  namespace: user-service-k8s-course
spec:
  type: NodePort
  ports:
    - name: 'node-port'
      nodePort: 30001
      port: 8080
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: post-service-ep
  namespace: post-service-k8s-course
spec:
  type: NodePort
  ports:
    - name: 'node-port'
      nodePort: 30002
      port: 8080
  selector:
    app: post-service