apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - post-service-deployment.yaml
  - user-service-deployment.yaml
  - database-deployment.yaml
  - external-access.yaml