apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: k8s-course
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: post-service
          image: epamilyaskumin/k8s-course_user-service:1.0.3
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 3
          envFrom:
            - configMapRef:
                name: k8s-course-configmap
            - secretRef:
                name: k8s-course-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  ports:
    - name: "default-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: user-service